# Generated by Django 6.0.1 on 2026-02-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=10)),
                ('location', models.CharField(choices=[('shepherd-union', 'Shepherd Union'), ('steward-library', 'Steward Library'), ('noorda-building', 'Noorda Building'), ('tracy-hall', 'Tracy Hall')], default='shepherd-union', max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('postedAt', models.DateTimeField(auto_now_add=True)),
                ('seller', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
