# Generated by Django 6.0.1 on 2026-02-23 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_category_tag_userprofile_display_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
