# Generated by Django 6.0.1 on 2026-03-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_feedback/'),
        ),
    ]
